# Generated by Django 5.0 on 2023-12-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='nombre',
            new_name='nombre_stock',
        ),
    ]
