# Generated by Django 5.0 on 2023-12-08 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_nombre_stock_nombre_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='nombre_stock',
            new_name='stock',
        ),
    ]
