# Generated by Django 5.0 on 2023-12-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categoria',
        ),
    ]
