# Generated by Django 5.0 on 2023-12-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
